config/routes.rb
Rails.application.routes.draw do
  resources :sites
  get 'sites/index'
  root 'sites#index'

  resources :sites do
    resources :visits
  end

end

app/models/site.rb
class Site < ActiveRecord::Base
	has_one :visit
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  belongs_to :site
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/sites_controller.rb
class SitesController < ApplicationController
  def index
    @sites = Site.all
    @visits = Visit.all
  end

  def show
    @site = Site.find(params[:id])
  end

  def new
  end

  def create
    @site = Site.new(site_params)
    @site.id = @site.title
    @site.save
    @site.visit = Visit.new(count: 0)
    redirect_to @site
  end

  private
    def site_params
      params.require(:site).permit(:title)
    end
end

app/controllers/visits_controller.rb
class VisitsController < ApplicationController
  def index
    if Site.exists?(params[:site_id])
	@visit = Site.find(params[:site_id]).visit
        @visit.count = @visit.count + 1
        @visit.save
    else
        @site = Site.new
        @site.id = params[:site_id]
	@site.title = @site.id
        @site.save
        @site.visit = Visit.new(count: 1)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sites_helper.rb
module SitesHelper
end

app/helpers/visits_helper.rb
module VisitsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ProjectonePhaseone</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sites/index.html.erb
<h1>Listing Sites</h1>
 
<table>
  <tr>
	  <th>ID</th>
	  <th>Number of visits</th>
  </tr>
 
  <% @sites.each do |site| %>
    <tr>
	    <td><%= site.id %></td>
	    <td><%= site.visit.count %></td>
    </tr>
  <% end %>
</table>

app/views/sites/new.html.erb
<h1>New Site</h1>

<%= form_for :site, url: sites_path do |f| %>
  <p>
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </p>

  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/sites/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @site.title %>
</p>

app/views/visits/index.html.erb
<h1>Thank you for visiting the site!</h1>